### ISSUE TITLE
Error handling falls short

### ISSUE THREAD

**Issue by Alex005** [papernotes/socsjs#2]
It seems like most (all?) of the `Promise.reject` methods in `schedule.js` return with a value of `null`. I'd love to see them either return a stack trace or maybe some information about what caused the Promise rejection (replace `null` with `err`?). Leaving these as `null` is making my debug process a pain in the ass

**Comment by papernotes** [comment]
Improving error handling is one of my TODOs and I haven't found time to fix it recently.  
For now, you may be getting ```null``` from a query taking too long.

**Comment by papernotes** [comment]
Latest version has error message handling for timeouts and no internet connection.
Commits with error handling: 0d40ac53b2635ec08eafccfe18ef8b83eb7733a0 8e7e6e30699f2ff3d6fddac596b0b388bb9485d9
